server.port = ${FLIGHT_CLIENT_SERVER_PORT:5005}
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

google.maps.api-key=${GOOGLE_MAPS_API_KEY:}
flight.core.base-url=${FLIGHT_CORE_BASE_URL:http://localhost:5004/flight-service}
currency.exchange.base-url=${CURRENCY_EXCHANGE_BASE_URL:http://localhost:5003}