server.port=${CURRENCY_EXCHANGE_SERVER_PORT:5003}
exchange.provider.base-url=${EXCHANGE_RATE_PROVIDER_BASE_URL:https://api.frankfurter.app}
exchange.provider.connect-timeout=${EXCHANGE_RATE_CONNECT_TIMEOUT:3s}
exchange.provider.read-timeout=${EXCHANGE_RATE_READ_TIMEOUT:5s}